# Generated by Django 5.1.5 on 2026-02-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_delete_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='assignments/pdfs/')),
                ('json_file', models.FileField(upload_to='assignments/json/')),
                ('question_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
