# Generated by Django 5.1.5 on 2026-02-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher_teachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='app.teachersubject'),
        ),
    ]
