# Generated by Django 5.1.5 on 2026-02-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedassignment',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
