# Generated by Django 5.1.5 on 2026-03-18 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='understanding_score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
