# Generated by Django 5.1.5 on 2026-03-18 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_understanding_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedassignment',
            name='intelligence_level',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
