# Generated by Django 5.1.5 on 2026-03-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_generatedassignment_intelligence_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='GeneratedAssignment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
