# Generated by Django 5.1.5 on 2026-03-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sharelisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareListing',
        ),
    ]
