# Generated by Django 5.1.5 on 2026-04-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_transaction_userportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockuser',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
